In [1]:
%run Data_Analysis.ipynb
# telcompos= df.loc[telcom1['Churn'] == 1]
# telcomneg= df.loc[telcom1['Churn'] == 0]
telcom1 = telcom1.values.tolist()
# telcompos= telcompos.values.tolist()
# telcomneg= telcomneg.values.tolist()

Rows     :  7043
Columns  :  21
Rows     :  7032


<Figure size 500x500 with 1 Axes>

<Figure size 1500x800 with 1 Axes>

<Figure size 900x400 with 1 Axes>

<Figure size 900x400 with 1 Axes>

<Figure size 900x400 with 1 Axes>

<Figure size 1000x450 with 1 Axes>

/home/palak/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning:

Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.



Intercept: [-0.92127175]
Regression: [[ 0.26853038 -0.03313905 -0.19881939 -0.03390609 -1.01029561  0.14562706
   0.27214742 -0.50723111 -0.27726094 -0.13265448 -0.42481994 -0.60206404
   0.3813072  -0.13002586  0.02615304]]
Accuracy of logistic regression classifier on test set: 0.79
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1007
           1       0.66      0.54      0.59       400

   micro avg       0.79      0.79      0.79      1407
   macro avg       0.75      0.71      0.73      1407
weighted avg       0.78      0.79      0.78      1407

Accuracy of SVM classifier on test set: 0.80
Accuracy of ANN classifier on test set: 0.79
Accuracy of logistic regression classifier on test set: 0.78
              precision    recall  f1-score   support

           0       0.79      0.75      0.77      1034
           1       0.76      0.81      0.78      1032

   micro avg       0.78      0.78      0.78      2066
   macro avg      

/home/palak/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning:

Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.



Accuracy of decision tree unpruned classifier on test set: 0.78
Accuracy of random forest classifier on test set: 0.77
Accuracy of random forest classifier on test set: 0.91
Accuracy of random forest classifier on test set: 0.77


/home/palak/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning:

The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.

/home/palak/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning:

The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.

/home/palak/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning:

The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.



In [2]:
telcom1

[[0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 29.85, 0],
 [0, 0, 0, 34, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 56.95, 0],
 [0, 0, 0, 2, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 53.85, 1],
 [0, 0, 0, 45, 0, 0, 1, 1, 0, 1, 1, 1, 0, 2, 42.3, 0],
 [0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 70.7, 1],
 [0, 0, 0, 8, 1, 1, 2, 0, 0, 1, 0, 0, 1, 0, 99.65, 1],
 [0, 0, 1, 22, 1, 1, 2, 0, 1, 0, 0, 0, 1, 3, 89.1, 0],
 [0, 0, 0, 10, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 29.75, 0],
 [0, 1, 0, 28, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 104.8, 1],
 [0, 0, 1, 62, 1, 0, 1, 1, 1, 0, 0, 1, 0, 2, 56.15, 0],
 [0, 1, 1, 13, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 49.95, 0],
 [0, 0, 0, 16, 1, 0, 0, 0, 0, 0, 0, 2, 0, 3, 18.95, 0],
 [0, 1, 0, 58, 1, 1, 2, 0, 0, 1, 0, 1, 0, 3, 100.35, 0],
 [0, 0, 0, 49, 1, 1, 2, 0, 1, 1, 0, 0, 1, 2, 103.7, 1],
 [0, 0, 0, 25, 1, 0, 2, 1, 0, 1, 1, 0, 1, 0, 105.5, 0],
 [0, 1, 1, 69, 1, 1, 2, 1, 1, 1, 1, 2, 0, 3, 113.25, 0],
 [0, 0, 0, 52, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 20.65, 0],
 [0, 0, 1, 71, 1, 1, 2, 1, 0, 1, 0, 2, 0, 2, 106.7, 0

In [3]:
telcompos=[]
telcomneg=[]
for i in range(0,len(telcom1)):
    if telcom1[i][15]==1:
        telcompos.append(telcom1[i])
    else:
        telcomneg.append(telcom1[i])
        

In [4]:
len(telcompos)

1869

In [20]:
import DecisionTree

In [32]:
#!/usr/bin/env python3

import CSVReader
import logging
import random
from concurrent.futures import ProcessPoolExecutor
from DecisionTree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import scikitplot as skplt
from numpy  import array


class RandomForestClassifier(object):

    """
    :param  nb_trees:       Number of decision trees to use
    :param  nb_samples:     Number of samples to give to each tree
    :param  max_depth:      Maximum depth of the trees
    :param  max_workers:    Maximum number of processes to use for training
    """
    def __init__(self, nb_trees, nb_samples, max_depth=-1, max_workers=1):
        self.trees = []
        self.nb_trees = nb_trees
        self.nb_samples = nb_samples
        self.max_depth = max_depth
        self.max_workers = max_workers
        self.alpha = random.uniform(0.25, 0.35)
    
    def sampler(self, data):
            alpha = random.uniform(0.25, 0.35)
            positive = random.sample(telcompos, int(alpha*self.nb_samples))
            negative = random.sample(telcomneg, int((1-alpha)*self.nb_samples)+1)
            total = positive+negative
            return total
    """
    Trains self.nb_trees number of decision trees.
    :param  data:   A list of lists with the last element of each list being
                    the value to predict
    """
    def fit(self, data):
        with ProcessPoolExecutor(max_workers=self.max_workers) as executor:
            rand_fts = map(lambda x: [x, self.sampler(data)], range(self.nb_trees))
            self.trees = list(executor.map(self.train_tree, rand_fts))

    """
    Trains a single tree and returns it.
    :param  data:   A List containing the index of the tree being trained
                    and the data to train it
    """
    def train_tree(self, data):
        
        logging.info('Training tree {}'.format(data[0] + 1))
        tree = DecisionTreeClassifier(max_depth=self.max_depth)

        tree.fit(data[1])
        return tree

    """
    Returns a prediction for the given feature. The result is the value that
    gets the most votes.
    :param  feature:    The features used to predict
    """
    def predict(self, feature):
        alpha = random.uniform(0.25, 0.35)
        churn_weight = 1 - alpha
        non_churn_weight = alpha
        predictions = []
        for tree in self.trees:
            predictions.append(tree.predict(feature))
        
        result = (predictions.count(1)* churn_weight +  predictions.count(0)* non_churn_weight)/60    
        #print(result)  
        if result>=0.5:
            return result,1
        else:
            return result,0

        

def test_rf():
    from sklearn.model_selection import train_test_split

    #data = CSVReader.read_csv("income.csv")
    data= telcom1
    print(type(data))
    train, test = train_test_split(data, test_size=0.3)

    rf = RandomForestClassifier(nb_trees=60, nb_samples=2400, max_workers=4)
    rf.fit(train)

    errors = 0
    features = [ft[:-1] for ft in test]
    values = [ft[-1] for ft in test]
    tp=0
    tn=0
    fp=0
    fn=0
    
    
    probab=[]
    pro=[]
    for feature, value in zip(features, values):
        prob, prediction = rf.predict(feature)
        pro.append(prob)
        pro.append(1-prob)
        probab.append(pro)
        if prediction != value:
            errors += 1
        if prediction == 0 and value==0:
            tn=tn+1
        if prediction == 1 and value==1:
            tp=tp+1
        if prediction == 0 and value==1:
            fn=fn+1
        if prediction == 1 and value==0:
            fp=fp+1
    probab= array(probab)
    values= array(values)
    print(probab)   
    print(values)
    logging.info("Error rate: {}".format(errors / len(features) * 100))
    print("Error rate: {}".format(errors / len(features) * 100))
    print("Accuracy: {}".format(100-errors / len(features) * 100))
    print("Accuracy-cf: {}".format((tp+tn) / len(features) ))
    print("Lift: {}".format((tp*len(features))/((tp+fp)*(tp+fn))))
    print("Precision-cf: {}".format(tp / (tp+fp) ))
    print("Recall-cf: {}".format(tp/ (tp+fn) ))

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    test_rf()

<class 'list'>


INFO:root:Training tree 1
INFO:root:Training tree 2
INFO:root:Training tree 3
INFO:root:Training tree 4
INFO:root:Training tree 5
INFO:root:Training tree 6
INFO:root:Training tree 7
INFO:root:Training tree 8
INFO:root:Training tree 9
INFO:root:Training tree 10
INFO:root:Training tree 11
INFO:root:Training tree 12
INFO:root:Training tree 13
INFO:root:Training tree 14
INFO:root:Training tree 15
INFO:root:Training tree 16
INFO:root:Training tree 17
INFO:root:Training tree 18
INFO:root:Training tree 19
INFO:root:Training tree 20
INFO:root:Training tree 21
INFO:root:Training tree 22
INFO:root:Training tree 23
INFO:root:Training tree 24
INFO:root:Training tree 25
INFO:root:Training tree 26
INFO:root:Training tree 27
INFO:root:Training tree 28
INFO:root:Training tree 29
INFO:root:Training tree 30
INFO:root:Training tree 31
INFO:root:Training tree 32
INFO:root:Training tree 33
INFO:root:Training tree 34
INFO:root:Training tree 35
INFO:root:Training tree 36
INFO:root:Training tree 37
INFO:root:

[[0.37955066 0.62044934 0.35234009 ... 0.66563478 0.25856044 0.74143956]
 [0.37955066 0.62044934 0.35234009 ... 0.66563478 0.25856044 0.74143956]
 [0.37955066 0.62044934 0.35234009 ... 0.66563478 0.25856044 0.74143956]
 ...
 [0.37955066 0.62044934 0.35234009 ... 0.66563478 0.25856044 0.74143956]
 [0.37955066 0.62044934 0.35234009 ... 0.66563478 0.25856044 0.74143956]
 [0.37955066 0.62044934 0.35234009 ... 0.66563478 0.25856044 0.74143956]]
[0 0 0 ... 0 0 0]
Error rate: 5.592417061611375
Accuracy: 94.40758293838863
Accuracy-cf: 0.9440758293838862
Lift: 3.544000714732422
Precision-cf: 0.8818011257035647
Recall-cf: 0.8952380952380953
